package org.nearbyshops.DAOsRemaining;


import org.nearbyshops.JDBCContract;
import org.nearbyshops.ModelSettings.ServiceConfiguration;

import java.sql.*;
import java.util.ArrayList;


public class ServiceConfigurationDAO {

	
	@Override
	protected void finalize() throws Throwable {
		// TODO Auto-generated method stub
		super.finalize();	
	}
	



	
	public int saveService(ServiceConfiguration serviceConfiguration)
	{

		Connection conn = null;
		Statement stmt = null;
		int rowIdOfInsertedRow = -1;

		String insertItemCategory = "INSERT INTO "
				+ ServiceConfiguration.TABLE_NAME
				+ "("

				+ ServiceConfiguration.IMAGE_PATH + ","
				+ ServiceConfiguration.LOGO_IMAGE_PATH + ","
				+ ServiceConfiguration.BACKDROP_IMAGE_PATH + ","

				+ ServiceConfiguration.SERVICE_NAME + ","
				+ ServiceConfiguration.HELPLINE_NUMBER + ","
				+ ServiceConfiguration.ADDRESS + ","

				+ ServiceConfiguration.CITY + ","
				+ ServiceConfiguration.PINCODE + ","
				+ ServiceConfiguration.LANDMARK + ","

				+ ServiceConfiguration.STATE + ","
				+ ServiceConfiguration.COUNTRY + ","
				+ ServiceConfiguration.ISO_COUNTRY_CODE + ","

				+ ServiceConfiguration.ISO_LANGUAGE_CODE + ","
				+ ServiceConfiguration.SERVICE_TYPE + ","
				+ ServiceConfiguration.SERVICE_LEVEL + ","

				+ ServiceConfiguration.LAT_CENTER + ","
				+ ServiceConfiguration.LON_CENTER + ","
				+ ServiceConfiguration.SERVICE_RANGE + ","

				+ ServiceConfiguration.LAT_MAX + ","
				+ ServiceConfiguration.LON_MAX + ","
				+ ServiceConfiguration.LAT_MIN + ","
				+ ServiceConfiguration.LON_MIN + ","

				+ ServiceConfiguration.UPDATED + ","

				+ " ) VALUES ( "

				+ "'" + serviceConfiguration.getImagePath()	+ "',"
				+ "'" + serviceConfiguration.getLogoImagePath()	+ "',"
				+ "'" + serviceConfiguration.getBackdropImagePath()	+ "',"

				+ "'" + serviceConfiguration.getServiceName()	+ "',"
				+ "'" + serviceConfiguration.getHelplineNumber()	+ "',"
				+ "'" + serviceConfiguration.getAddress()	+ "',"

				+ "'" + serviceConfiguration.getCity()	+ "',"
				+ "" + serviceConfiguration.getPincode()	+ ","
				+ "'" + serviceConfiguration.getLandmark()	+ "',"

				+ "'" + serviceConfiguration.getState()	+ "',"
				+ "'" + serviceConfiguration.getCountry()	+ "',"
				+ "'" + serviceConfiguration.getISOCountryCode()	+ "',"

				+ "'" + serviceConfiguration.getISOLanguageCode()	+ "',"
				+ "" + serviceConfiguration.getServiceType()	+ ","
				+ "" + serviceConfiguration.getServiceLevel()	+ ","

				+ "" + serviceConfiguration.getLatCenter()	+ ","
				+ "" + serviceConfiguration.getLonCenter()	+ ","
				+ "" + serviceConfiguration.getServiceRange()	+ ","

				+ "" + serviceConfiguration.getLatMax()	+ ","

				+ "" + serviceConfiguration.getLonMax()	+ ","
				+ "" + serviceConfiguration.getLatMin()	+ ","
				+ "" + serviceConfiguration.getLonMin()	+ ","

				+ "'" + "now()"	+ "',"
				+ ")";
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowIdOfInsertedRow = stmt.executeUpdate(insertItemCategory,Statement.RETURN_GENERATED_KEYS);
			
			ResultSet rs = stmt.getGeneratedKeys();

			if(rs.next())
			{
				rowIdOfInsertedRow = rs.getInt(1);
			}
			
			
			
			System.out.println("Key autogenerated Save CurrentServiceConfiguration: " + rowIdOfInsertedRow);
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		
		return rowIdOfInsertedRow;
	}




	public int updateService(ServiceConfiguration serviceConfiguration)
	{	
		String updateStatement = "UPDATE " + ServiceConfiguration.TABLE_NAME

				+ " SET "

				+ ServiceConfiguration.IMAGE_PATH + " = " + "'" + serviceConfiguration.getImagePath() + "'" + ","
				+ ServiceConfiguration.LOGO_IMAGE_PATH + " = " + "'" + serviceConfiguration.getLogoImagePath() + "'" + ","
				+ ServiceConfiguration.BACKDROP_IMAGE_PATH + " = " + "'" + serviceConfiguration.getBackdropImagePath() + "'" + ","

				+ ServiceConfiguration.SERVICE_NAME + " = " + "'" + serviceConfiguration.getServiceName() + "'" + ","
				+ ServiceConfiguration.HELPLINE_NUMBER + " = " + "'" + serviceConfiguration.getHelplineNumber() + "'" + ","
				+ ServiceConfiguration.ADDRESS + " = " + "'" + serviceConfiguration.getAddress() + "'" + ","

				+ ServiceConfiguration.CITY + " = " + "'" + serviceConfiguration.getCity() + "'" + ","
				+ ServiceConfiguration.PINCODE + " = " + "" + serviceConfiguration.getPincode() + "" + ","
				+ ServiceConfiguration.LANDMARK + " = " + "'" + serviceConfiguration.getLandmark() + "'" + ","

				+ ServiceConfiguration.STATE + " = " + "'" + serviceConfiguration.getState() + "'" + ","
				+ ServiceConfiguration.COUNTRY + " = " + "'" + serviceConfiguration.getCountry() + "'" + ","
				+ ServiceConfiguration.ISO_COUNTRY_CODE + " = " + "'" + serviceConfiguration.getISOCountryCode() + "'" + ","

				+ ServiceConfiguration.ISO_LANGUAGE_CODE + " = " + "'" + serviceConfiguration.getISOLanguageCode() + "'" + ","
				+ ServiceConfiguration.SERVICE_TYPE + " = " + "" + serviceConfiguration.getServiceType() + "" + ","
				+ ServiceConfiguration.SERVICE_LEVEL + " = " + "" + serviceConfiguration.getServiceLevel() + "" + ","

				+ ServiceConfiguration.LAT_CENTER + " = " + "" + serviceConfiguration.getLatCenter() + "" + ","
				+ ServiceConfiguration.LON_CENTER + " = " + "" + serviceConfiguration.getLonCenter() + "" + ","
				+ ServiceConfiguration.SERVICE_RANGE + " = " + "" + serviceConfiguration.getServiceRange() + "" + ","

				+ ServiceConfiguration.LAT_MAX + " = " + "" + serviceConfiguration.getLatMax() + "" + ","

				+ ServiceConfiguration.LON_MAX + " = " + "" + serviceConfiguration.getLonMax() + "" + ","
				+ ServiceConfiguration.LAT_MIN + " = " + "" + serviceConfiguration.getLatMin() + "" + ","
				+ ServiceConfiguration.LON_MIN + " = " + "" + serviceConfiguration.getLonMin() + "" + ","

				+ ServiceConfiguration.UPDATED + " = " + "'" + "now()" + "'" + ","

				+ " WHERE "

				+ ServiceConfiguration.SERVICE_CONFIGURATION_ID + " = " + 1;


		Connection conn = null;
		Statement stmt = null;
		int updatedRows = -1;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			updatedRows = stmt.executeUpdate(updateStatement);
			
			
			System.out.println("Total rows updated: " + updatedRows);	
			
			//conn.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return updatedRows;
		
	}




	public int deleteService(int serviceID)
	{
		
		String deleteStatement = "DELETE FROM " + ServiceConfiguration.TABLE_NAME + " WHERE " + ServiceConfiguration.SERVICE_CONFIGURATION_ID + " = "
				+ serviceID;
		
		
		Connection conn= null;
		Statement stmt = null;
		int rowsCountDeleted = 0;
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowsCountDeleted = stmt.executeUpdate(deleteStatement);
			
			System.out.println(" Deleted Count: " + rowsCountDeleted);	
			
			conn.close();	
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		
		return rowsCountDeleted;
	}
	


	
	
	
	public ArrayList<ServiceConfiguration> readServices(Integer serviceLevel, Integer serviceType,
																			  Double latCenterQuery, Double lonCenterQuery,
																			  String sortBy,
																			  int limit, int offset)
	{


		String queryNormal = "SELECT " + " 6371 * acos(cos( radians("
							+ latCenterQuery + ")) * cos( radians( " + ServiceConfiguration.LAT_CENTER
							+ ")) * cos(radians( "
							+ ServiceConfiguration.LON_CENTER + ") - radians(" + lonCenterQuery + "))"
							+ " + sin( radians(" + latCenterQuery+ ")) * sin(radians(" + ServiceConfiguration.LAT_CENTER + "))) as distance" + ","
							+ " * FROM " + ServiceConfiguration.TABLE_NAME;


		boolean isFirst = true;


		if(serviceLevel > 0)
		{
			queryNormal = queryNormal + " WHERE " + ServiceConfiguration.SERVICE_LEVEL + " = " + serviceLevel;

			isFirst = false;
		}



		if(serviceType > 0 )
		{
			if(isFirst)
			{
				queryNormal = queryNormal + " WHERE " + ServiceConfiguration.SERVICE_TYPE + " = " + serviceType;

				isFirst = false;

			}else
			{
				queryNormal = queryNormal + " AND " + ServiceConfiguration.SERVICE_TYPE + " = " + serviceType;

			}

		}



		// apply visibility filter


		if(latCenterQuery!=null && lonCenterQuery!=null)
		{

			String queryPartVisibilityFilter = "";




			// filter using Haversine formula using SQL math functions
			queryPartVisibilityFilter = queryPartVisibilityFilter
					+ " (6371.01 * acos(cos( radians("
					+ latCenterQuery
					+ ")) * cos( radians("
					+ ServiceConfiguration.LAT_CENTER
					+ " )) * cos(radians( "
					+ ServiceConfiguration.LON_CENTER
					+ ") - radians("
					+ lonCenterQuery
					+ "))"
					+ " + sin( radians("
					+ latCenterQuery
					+ ")) * sin(radians("
					+ ServiceConfiguration.LAT_CENTER
					+ ")))) <= "
					+ ServiceConfiguration.SERVICE_RANGE ;





			if(isFirst)
			{
				queryNormal = queryNormal + " WHERE ";

				// reset the flag
				isFirst = false;

			}else
			{
				queryNormal = queryNormal + " AND ";
			}



			queryNormal = queryNormal + queryPartVisibilityFilter;


		}





		if(sortBy!=null)
		{
			if(!sortBy.equals(""))
			{
				String queryPartSortBy = " ORDER BY " + sortBy;

				queryNormal = queryNormal + queryPartSortBy;
			}
		}



		if(limit > 0)
		{

			String queryPartLimitOffset = "";

			if(offset>0)
			{
				queryPartLimitOffset = " LIMIT " + limit + " " + " OFFSET " + offset;

			}else
			{
				queryPartLimitOffset = " LIMIT " + limit + " " + " OFFSET " + 0;
			}


			queryNormal = queryNormal + queryPartLimitOffset;
		}



		ArrayList<ServiceConfiguration> servicesList = new ArrayList<ServiceConfiguration>();
		
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL
					,JDBCContract.CURRENT_USERNAME
					, JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(queryNormal);
			
			while(rs.next())
			{
				ServiceConfiguration serviceConfiguration = new ServiceConfiguration();

				serviceConfiguration.setRt_distance(rs.getDouble("distance"));

				serviceConfiguration.setServiceID(rs.getInt(ServiceConfiguration.SERVICE_CONFIGURATION_ID));
				serviceConfiguration.setImagePath(rs.getString(ServiceConfiguration.IMAGE_PATH));
				serviceConfiguration.setLogoImagePath(rs.getString(ServiceConfiguration.LOGO_IMAGE_PATH));

				serviceConfiguration.setBackdropImagePath(rs.getString(ServiceConfiguration.BACKDROP_IMAGE_PATH));
				serviceConfiguration.setServiceName(rs.getString(ServiceConfiguration.SERVICE_NAME));
				serviceConfiguration.setHelplineNumber(rs.getString(ServiceConfiguration.HELPLINE_NUMBER));

				serviceConfiguration.setAddress(rs.getString(ServiceConfiguration.ADDRESS));
				serviceConfiguration.setCity(rs.getString(ServiceConfiguration.CITY));
				serviceConfiguration.setPincode(rs.getLong(ServiceConfiguration.PINCODE));

				serviceConfiguration.setLandmark(rs.getString(ServiceConfiguration.LANDMARK));
				serviceConfiguration.setState(rs.getString(ServiceConfiguration.STATE));
				serviceConfiguration.setCountry(rs.getString(ServiceConfiguration.COUNTRY));

				serviceConfiguration.setISOCountryCode(rs.getString(ServiceConfiguration.ISO_COUNTRY_CODE));
				serviceConfiguration.setISOLanguageCode(rs.getString(ServiceConfiguration.ISO_LANGUAGE_CODE));
				serviceConfiguration.setServiceType(rs.getInt(ServiceConfiguration.SERVICE_TYPE));

				serviceConfiguration.setServiceLevel(rs.getInt(ServiceConfiguration.SERVICE_LEVEL));
				serviceConfiguration.setLatCenter(rs.getDouble(ServiceConfiguration.LAT_CENTER));
				serviceConfiguration.setLonCenter(rs.getDouble(ServiceConfiguration.LON_CENTER));

				serviceConfiguration.setServiceRange(rs.getInt(ServiceConfiguration.SERVICE_RANGE));

				serviceConfiguration.setLatMax(rs.getDouble(ServiceConfiguration.LAT_MAX));
				serviceConfiguration.setLonMax(rs.getDouble(ServiceConfiguration.LON_MAX));
				serviceConfiguration.setLatMin(rs.getDouble(ServiceConfiguration.LAT_MIN));

				serviceConfiguration.setLonMin(rs.getDouble(ServiceConfiguration.LON_MIN));

				serviceConfiguration.setCreated(rs.getTimestamp(ServiceConfiguration.CREATED));
				serviceConfiguration.setUpdated(rs.getTimestamp(ServiceConfiguration.UPDATED));


				servicesList.add(serviceConfiguration);
				
			}
			

			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		

		finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
								
		return servicesList;
	}





	public ServiceConfiguration readService(int serviceID)
	{
		
		String query = "SELECT * FROM " + ServiceConfiguration.TABLE_NAME
						+ " WHERE " + ServiceConfiguration.SERVICE_CONFIGURATION_ID + " = " + serviceID;
		
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;


		ServiceConfiguration serviceConfiguration = null;

		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(query);
			
			while(rs.next())
			{
				serviceConfiguration = new ServiceConfiguration();

				serviceConfiguration.setServiceID(rs.getInt(ServiceConfiguration.SERVICE_CONFIGURATION_ID));
				serviceConfiguration.setImagePath(rs.getString(ServiceConfiguration.IMAGE_PATH));
				serviceConfiguration.setLogoImagePath(rs.getString(ServiceConfiguration.LOGO_IMAGE_PATH));

				serviceConfiguration.setBackdropImagePath(rs.getString(ServiceConfiguration.BACKDROP_IMAGE_PATH));
				serviceConfiguration.setServiceName(rs.getString(ServiceConfiguration.SERVICE_NAME));
				serviceConfiguration.setHelplineNumber(rs.getString(ServiceConfiguration.HELPLINE_NUMBER));

				serviceConfiguration.setAddress(rs.getString(ServiceConfiguration.ADDRESS));
				serviceConfiguration.setCity(rs.getString(ServiceConfiguration.CITY));
				serviceConfiguration.setPincode(rs.getLong(ServiceConfiguration.PINCODE));

				serviceConfiguration.setLandmark(rs.getString(ServiceConfiguration.LANDMARK));
				serviceConfiguration.setState(rs.getString(ServiceConfiguration.STATE));
				serviceConfiguration.setCountry(rs.getString(ServiceConfiguration.COUNTRY));

				serviceConfiguration.setISOCountryCode(rs.getString(ServiceConfiguration.ISO_COUNTRY_CODE));
				serviceConfiguration.setISOLanguageCode(rs.getString(ServiceConfiguration.ISO_LANGUAGE_CODE));
				serviceConfiguration.setServiceType(rs.getInt(ServiceConfiguration.SERVICE_TYPE));

				serviceConfiguration.setServiceLevel(rs.getInt(ServiceConfiguration.SERVICE_LEVEL));
				serviceConfiguration.setLatCenter(rs.getDouble(ServiceConfiguration.LAT_CENTER));
				serviceConfiguration.setLonCenter(rs.getDouble(ServiceConfiguration.LON_CENTER));

				serviceConfiguration.setServiceRange(rs.getInt(ServiceConfiguration.SERVICE_RANGE));

				serviceConfiguration.setLatMax(rs.getDouble(ServiceConfiguration.LAT_MAX));
				serviceConfiguration.setLonMax(rs.getDouble(ServiceConfiguration.LON_MAX));
				serviceConfiguration.setLatMin(rs.getDouble(ServiceConfiguration.LAT_MIN));

				serviceConfiguration.setLonMin(rs.getDouble(ServiceConfiguration.LON_MIN));

				serviceConfiguration.setCreated(rs.getTimestamp(ServiceConfiguration.CREATED));
				serviceConfiguration.setUpdated(rs.getTimestamp(ServiceConfiguration.UPDATED));


			}
			
			
			//System.out.println("Total itemCategories queried " + itemCategoryList.size());	
	
		
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		return serviceConfiguration;
	}	
}
