package org.nearbyshops.DAOs;

import org.nearbyshops.ContractClasses.CartContract;
import org.nearbyshops.ContractClasses.JDBCContract;
import org.nearbyshops.ContractClasses.ServiceConfigurationContract;
import org.nearbyshops.Model.Cart;
import org.nearbyshops.Model.ServiceConfiguration;

import java.sql.*;
import java.util.ArrayList;


public class ServiceConfigDAO {

	
	@Override
	protected void finalize() throws Throwable {
		// TODO Auto-generated method stub
		super.finalize();	
	}
	



	
	public int saveConfig(ServiceConfiguration serviceConfiguration)
	{

		Connection conn = null;
		Statement stmt = null;
		int rowIdOfInsertedRow = -1;

		String insertStatement = "INSERT INTO "
				+ ServiceConfigurationContract.TABLE_NAME
				+ "("
				+ ServiceConfigurationContract.NAME + ","
				+ ServiceConfigurationContract.SERVICE_ID + ""
				+ " ) VALUES ( "
				+ "" + serviceConfiguration.getName()	+ ","
				+ "" + serviceConfiguration.getServiceID() + ""
				+ ")";
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowIdOfInsertedRow = stmt.executeUpdate(insertStatement,Statement.RETURN_GENERATED_KEYS);
			
			ResultSet rs = stmt.getGeneratedKeys();

			if(rs.next())
			{
				rowIdOfInsertedRow = rs.getInt(1);
			}
			
			
			
			System.out.println("Key autogenerated Save ServiceConfig: " + rowIdOfInsertedRow);
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		
		return rowIdOfInsertedRow;
	}
	

	public int updateServiceConfig(ServiceConfiguration serviceConfiguration)
	{	
		String updateStatement = "UPDATE " + ServiceConfigurationContract.TABLE_NAME
				+ " SET "
				+ ServiceConfigurationContract.NAME + " = " + "'" + serviceConfiguration.getName() + "'" + ","
				+ "" + ServiceConfigurationContract.SERVICE_ID + " = " + "" + serviceConfiguration.getServiceID() + ""
				+ " WHERE "
				+ ServiceConfigurationContract.CONFIGURATION_ID + " = " + serviceConfiguration.getConfigurationID();


		Connection conn = null;
		Statement stmt = null;
		int updatedRows = -1;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			updatedRows = stmt.executeUpdate(updateStatement);
			
			
			System.out.println("Total rows updated: " + updatedRows);	
			
			//conn.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return updatedRows;
		
	}
	

	public int deleteServiceConfiguration(int configID)
	{
		
		String deleteStatement =
				"DELETE FROM " + ServiceConfigurationContract.TABLE_NAME
				+ " WHERE "
				+ ServiceConfigurationContract.CONFIGURATION_ID + " = " + configID;
		
		
		Connection conn= null;
		Statement stmt = null;
		int rowsCountDeleted = 0;
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowsCountDeleted = stmt.executeUpdate(deleteStatement);
			
			System.out.println(" Deleted Count: " + rowsCountDeleted);	
			
			conn.close();	
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		
		return rowsCountDeleted;
	}
	
	
	
	
	
	public ArrayList<ServiceConfiguration> readServiceConfig(int endUserID,int shopID)
	{
		String query = "SELECT * FROM " + CartContract.TABLE_NAME;

		boolean isFirst = true;

		if(endUserID > 0)
		{
			query = query + " WHERE " + CartContract.END_USER_ID + " = " + endUserID;

			isFirst = false;
		}

		if(shopID > 0 )
		{
			if(isFirst)
			{
				query = query + " WHERE " + CartContract.SHOP_ID + " = " + shopID;

			}else
			{
				query = query + " AND " + CartContract.SHOP_ID + " = " + shopID;

			}

		}



		ArrayList<Cart> cartsList = new ArrayList<Cart>();
		
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL
					,JDBCContract.CURRENT_USERNAME
					, JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(query);
			
			while(rs.next())
			{

				Cart cart = new Cart();

				cart.setCartID(rs.getInt(CartContract.CART_ID));
				cart.setEndUserID(rs.getInt(CartContract.END_USER_ID));
				cart.setShopID(rs.getInt(CartContract.SHOP_ID));

				cartsList.add(cart);
				
			}
			

			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		

		finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
								
		return null;
	}

	
	public ServiceConfiguration readConfig(int configID)
	{
		
		String query = "SELECT * FROM " + ServiceConfigurationContract.TABLE_NAME
						+ " WHERE " + ServiceConfigurationContract.CONFIGURATION_ID + " = " + configID;


		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;

		//Cart cart = null;
		ServiceConfiguration serviceConfiguration = null;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(query);
			
			while(rs.next())
			{

				serviceConfiguration = new ServiceConfiguration();

				serviceConfiguration.setConfigurationID(rs.getInt(ServiceConfigurationContract.CONFIGURATION_ID));
				serviceConfiguration.setName(rs.getString(ServiceConfigurationContract.NAME));
				serviceConfiguration.setServiceID(rs.getInt(ServiceConfigurationContract.SERVICE_ID));

			}
			
			
			//System.out.println("Total itemCategories queried " + itemCategoryList.size());	
	
		
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		return serviceConfiguration;
	}	
}
