package org.nearbyshops.DAOs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import org.nearbyshops.ContractClasses.JDBCContract;
import org.nearbyshops.ContractClasses.ShopContract;
import org.nearbyshops.Model.Shop;
import org.nearbyshops.Utility.GeoLocation;

public class ShopService {
	
	
	public int insertShop(Shop shop)
	{
		
		Connection conn = null;
		Statement stmt = null;
		int rowIdOfInsertedRow = -1;

		String insertShop = "INSERT INTO "
				+ ShopContract.TABLE_NAME				
				+ "("  
				+ ShopContract.SHOP_NAME + ","
				+ ShopContract.DELIVERY_CHARGES + ","
				+ ShopContract.DISTRIBUTOR_ID + ","
				+ ShopContract.LAT_CENTER + ","
				+ ShopContract.LON_CENTER + ","
				+ ShopContract.DELIVERY_RANGE + ","
				+ ShopContract.LON_MAX + ","
				+ ShopContract.LAT_MAX + ","
				+ ShopContract.LON_MIN + ","
				+ ShopContract.LAT_MIN + ","
				+ ShopContract.IMAGE_PATH + ""
				+ " ) VALUES ("
				+ "'" + shop.getShopName() + "',"
				+ "" + shop.getDeliveryCharges() + ","
				+ "" + shop.getDistributorID() + ","
				+ "" + shop.getLatCenter() + ","
				+ "" + shop.getLonCenter() + ","
				+ "" + shop.getDeliveryRange() + ","
				+ "" + shop.getLonMax() + ","
				+ "" + shop.getLatMax() + ","
				+ "" + shop.getLonMin() + ","
				+ "" + shop.getLatMin() + ","
				+ "'" + shop.getImagePath() + "'" + ")";
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowIdOfInsertedRow = stmt.executeUpdate(insertShop,Statement.RETURN_GENERATED_KEYS);
			
			ResultSet rs = stmt.getGeneratedKeys();
			
			if(rs.next())
			{
				rowIdOfInsertedRow = rs.getInt(1);
			}
			
			
			
			System.out.println("Key autogenerated SaveShop: " + rowIdOfInsertedRow);
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		
		return rowIdOfInsertedRow;

	}
	
	
	public int updateShop(Shop shop)
	{
		
		
		String updateStatement = "UPDATE " + ShopContract.TABLE_NAME 
				+ " SET " + ShopContract.SHOP_NAME + " = "
				+ "'" + shop.getShopName() + "',"
				+ ShopContract.DELIVERY_CHARGES + " ="
				+ "" + shop.getDeliveryCharges() + ","
				+ ShopContract.DISTRIBUTOR_ID + " ="
				+ "" + shop.getDistributorID() + ","
				+ ShopContract.LAT_CENTER + " ="
				+ "" + shop.getLatCenter() + ","
				+ ShopContract.LON_CENTER + " ="
				+ "" + shop.getLonCenter() + ","
				+ ShopContract.DELIVERY_RANGE + " ="
				+ "" + shop.getDeliveryRange() + ","
				+ ShopContract.LON_MAX + " ="
				+ "" + shop.getLonMax() + ","
				+ ShopContract.LAT_MAX + " ="
				+ "" + shop.getLatMax() + ","
				+ ShopContract.LON_MIN + " ="
				+ "" + shop.getLonMin() + ","
				+ ShopContract.LAT_MIN + " ="
				+ "" + shop.getLatMin() + ","
				+ ShopContract.IMAGE_PATH + " ="
				+ "'" + shop.getImagePath() + "'"
				+ " WHERE " + ShopContract.SHOP_ID + " = "
				+ shop.getShopID();
		
		
		
		Connection conn = null;
		Statement stmt = null;
		int updatedRows = -1;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			updatedRows = stmt.executeUpdate(updateStatement);
			
			
			System.out.println("Total rows updated: " + updatedRows);	
			
			//conn.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return updatedRows;

	}
	
	
	public int deleteShop(int shopID)
	{
		
		String deleteStatement = "DELETE FROM " + ShopContract.TABLE_NAME 
				+ " WHERE " + ShopContract.SHOP_ID + "= " 
				+ shopID;
		
		
		Connection conn= null;
		Statement stmt = null;
		int rowCountDeleted = 0;
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowCountDeleted = stmt.executeUpdate(deleteStatement);
			
			System.out.println(" Deleted Count: " + rowCountDeleted);	
			
			conn.close();	
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		
		return rowCountDeleted;
	}



	GeoLocation center;

	GeoLocation[] minMaxArray;
	GeoLocation pointOne;
	GeoLocation pointTwo;


	public ArrayList<Shop> getShops(
			int distributorID,
			double latCenter, double lonCenter,
			double deliveryRangeMin,double deliveryRangeMax,
			double proximity
	)
	{

		// flag for tracking whether to put "AND" or "WHERE"
		boolean isFirst = true;

		String query = "SELECT * FROM " + ShopContract.TABLE_NAME;
		
		if(distributorID > 0)
		{
			query = query + " WHERE " 
					+ ShopContract.DISTRIBUTOR_ID + " = " + distributorID;

			// reset the flag
			isFirst = false;
		}


		if(latCenter>0 && latCenter>0)
		{
			// Applying shop visibility filter. Gives all the shops which are visible at the given location defined by
			// latCenter and lonCenter. For more information see the API documentation.

			if(isFirst)
			{
				query = query + " WHERE ";

				// reset the flag
				isFirst = false;

			}else
			{
				query = query + " AND ";
			}


			query = query + ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LAT_MAX
					+ " >= " + latCenter
					+ " AND "
					+ ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LAT_MIN
					+ " <= " + latCenter
					+ " AND "
					+ ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LON_MAX
					+ " >= " + lonCenter
					+ " AND "
					+ ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LON_MIN
					+ " <= " + lonCenter;

			//+ " BETWEEN " + latmax + " AND " + latmin;
		}



		if(deliveryRangeMin > 0|| deliveryRangeMax>0){

			// apply delivery range filter

			if(isFirst)
			{
				query = query + " WHERE ";

				// reset the flag
				isFirst = false;

			}else
			{
				query = query + " AND ";
			}


			query = query + ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.DELIVERY_RANGE
					+ " BETWEEN " + deliveryRangeMin + " AND " + deliveryRangeMax;
					//+ " <= " + deliveryRange;
		}


		// proximity cannot be greater than the delivery range if the delivery range is supplied. Otherwise this condition is
		// not required.
		if(proximity > 0 && (deliveryRangeMax==0 || (deliveryRangeMax > 0 && proximity <= deliveryRangeMax)))
		{
			// generate bounding coordinates for the shop based on the required location and its

			center = GeoLocation.fromDegrees(latCenter,lonCenter);
			minMaxArray = center.boundingCoordinates(proximity,6371.01);

			pointOne = minMaxArray[0];
			pointTwo = minMaxArray[1];

			double latMin = pointOne.getLatitudeInDegrees();
			double lonMin = pointOne.getLongitudeInDegrees();
			double latMax = pointTwo.getLatitudeInDegrees();
			double lonMax = pointTwo.getLongitudeInDegrees();


			// Make sure that shop center lies between the bounding coordinates generated by proximity bounding box

			if(isFirst)
			{
				query = query + " WHERE ";

				// reset the flag
				isFirst = false;

			}else
			{
				query = query + " AND ";
			}

			query = query + ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LAT_CENTER
					+ " < " + latMax

					+ " AND "
					+ ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LAT_CENTER
					+ " > " + latMin

					+ " AND "
					+ ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LON_CENTER
					+ " < " + lonMax

					+ " AND "
					+ ShopContract.TABLE_NAME
					+ "."
					+ ShopContract.LON_CENTER
					+ " > " + lonMin;
		}




		
		ArrayList<Shop> shopList = new ArrayList<Shop>();
		
		
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,
					JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(query);
			
			while(rs.next())
			{
				
				Shop shop = new Shop();
				shop.setShopID(rs.getInt(ShopContract.SHOP_ID));
				shop.setShopName(rs.getString(ShopContract.SHOP_NAME));
				shop.setLatCenter(rs.getFloat(ShopContract.LAT_CENTER));
				shop.setLonCenter(rs.getFloat(ShopContract.LON_CENTER));
				shop.setDeliveryCharges(rs.getFloat(ShopContract.DELIVERY_CHARGES));
				shop.setLatMax(rs.getDouble(ShopContract.LAT_MAX));
				shop.setLonMax(rs.getDouble(ShopContract.LON_MAX));
				shop.setLatMin(rs.getDouble(ShopContract.LAT_MIN));
				shop.setLonMin(rs.getDouble(ShopContract.LON_MIN));
				shop.setDistributorID(rs.getInt(ShopContract.DISTRIBUTOR_ID));
				shop.setDeliveryRange(rs.getDouble(ShopContract.DELIVERY_RANGE));
				shop.setImagePath(rs.getString(ShopContract.IMAGE_PATH));
				shopList.add(shop);
				
			}
			
			System.out.println("Total Shops queried " + shopList.size());


			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		

		finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
								
		return shopList;
	}
	
	
	
	public Shop getShop(int ShopID)
	{		
		String query = "SELECT * FROM " + ShopContract.TABLE_NAME 
						+ " WHERE "	+  ShopContract.SHOP_ID + "= " + ShopID;
		
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		Shop shop = null;
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,
					JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(query);
			
			
			while(rs.next())
			{
				
				shop = new Shop();
				shop.setShopID(rs.getInt(ShopContract.SHOP_ID));
				shop.setShopName(rs.getString(ShopContract.SHOP_NAME));
				shop.setLatCenter(rs.getFloat(ShopContract.LAT_CENTER));
				shop.setLonCenter(rs.getFloat(ShopContract.LON_CENTER));
				shop.setDeliveryCharges(rs.getFloat(ShopContract.DELIVERY_CHARGES));
				shop.setLatMax(rs.getDouble(ShopContract.LAT_MAX));
				shop.setLonMax(rs.getDouble(ShopContract.LON_MAX));
				shop.setLatMin(rs.getDouble(ShopContract.LAT_MIN));
				shop.setLonMin(rs.getDouble(ShopContract.LON_MIN));
				shop.setDistributorID(rs.getInt(ShopContract.DISTRIBUTOR_ID));
				shop.setDeliveryRange(rs.getDouble(ShopContract.DELIVERY_RANGE));
				shop.setImagePath(rs.getString(ShopContract.IMAGE_PATH));
				
			}
	
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		return shop;
	}
	
}
