package org.nearbyshops.Service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import org.nearbyshops.contractClasses.ItemCategoryContract;
import org.nearbyshops.contractClasses.ItemContract;
import org.nearbyshops.contractClasses.JDBCContract;
import org.nearbyshops.contractClasses.ShopContract;
import org.nearbyshops.contractClasses.ShopItemContract;
import org.nearbyshops.model.ShopItem;

public class ShopItemService {

	public int insertShopItem(ShopItem shopItem)
	{
		
		Connection conn = null;
		Statement stmt = null;
		int rowCount = -1;

		String insertShop = "INSERT INTO "
				+ ShopItemContract.TABLE_NAME				
				+ "("  
				+ ShopItemContract.SHOP_ID + ","
				+ ShopItemContract.QUANTITY_UNIT + ","
				+ ShopItemContract.QUANTITY_MULTIPLE + ","
				+ ShopItemContract.ITEM_PRICE + ","
				+ ShopItemContract.ITEM_ID + ","
				+ ShopItemContract.AVAILABLE_ITEM_QUANTITY
				+ " ) VALUES ("
				+ "" + shopItem.getShopID() + "," 
				+ "" + shopItem.getQuantityUnit() + "," 
				+ "" + shopItem.getQuantityMultiple() + ","
				+ "" + shopItem.getItemPrice() + ","
				+ "" + shopItem.getItemID() + ","
				+ "" + shopItem.getAvailableItemQuantity()
				+ ")";
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowCount = stmt.executeUpdate(insertShop,Statement.RETURN_GENERATED_KEYS);
			
			
			System.out.println("Key autogenerated SaveShop: Rows Inserted = " + rowCount);
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return rowCount;
	}
	
	
	
	public int updateShopItem(ShopItem shopItem)
	{
		String updateStatement = "UPDATE " + ShopItemContract.TABLE_NAME 
				+ " SET " + ShopItemContract.AVAILABLE_ITEM_QUANTITY + " = "
				+ "" + shopItem.getAvailableItemQuantity() + ","
				+ ShopItemContract.ITEM_ID + " ="
				+ "" + shopItem.getItemID() + ","
				+ ShopItemContract.ITEM_PRICE + " ="
				+ "" + shopItem.getItemPrice() + ","
				+ ShopItemContract.QUANTITY_MULTIPLE + " ="
				+ "" + shopItem.getQuantityMultiple() + ","
				+ ShopItemContract.QUANTITY_UNIT + " ="
				+ "'" + shopItem.getQuantityUnit() + "',"
				+ ShopItemContract.SHOP_ID + " ="
				+ "" + shopItem.getShopID() + ""
				+ " WHERE " + ShopItemContract.SHOP_ID + " = "
				+ shopItem.getShopID() + " AND "
				+ ShopItemContract.ITEM_ID + " = " 
				+ shopItem.getItemID();
		
		System.out.println("Query:" + updateStatement);
		
		
		Connection conn = null;
		Statement stmt = null;
		int updatedRows = -1;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
					JDBCContract.CURRENT_USERNAME,
					JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			updatedRows = stmt.executeUpdate(updateStatement);
			
			
			System.out.println("Total rows updated: " + updatedRows);	
			
			//conn.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		return updatedRows;
	}
	
	
	
	
	public int deleteShopItem(int shopID,int itemID)
	{
		String deleteStatement = "DELETE FROM " + ShopItemContract.TABLE_NAME 
				+ " WHERE " + ShopItemContract.SHOP_ID + " = " + shopID
				+ " AND " + ShopItemContract.ITEM_ID + " = " + itemID;
		
		
		Connection conn= null;
		Statement stmt = null;
		int rowsCountDeleted = 0;
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rowsCountDeleted = stmt.executeUpdate(deleteStatement);
			
			System.out.println(" Deleted Count: " + rowsCountDeleted);	
			
			conn.close();	
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		finally
		
		{
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	
		
		return rowsCountDeleted;
	}
	
	
	
	
public ArrayList<ShopItem> getShopItems(int shopID,int itemID,int itemCategoryID)
{
		
		// set this flag to false after setting the first query
		boolean isFirst = true;
		
		
		
		String queryOld = "SELECT * FROM " + ShopItemContract.TABLE_NAME;
	

		String query2 = "SELECT " 
			+ "SI." + ShopItemContract.ITEM_ID + ","
			+ "SI." + ShopItemContract.SHOP_ID + ","
			+ "SI." + ShopItemContract.ITEM_PRICE + ","
			+ "SI." + ShopItemContract.QUANTITY_MULTIPLE + ","
			+ "SI." + ShopItemContract.QUANTITY_UNIT + ","
			+ "SI." + ShopItemContract.AVAILABLE_ITEM_QUANTITY + ""
			+ " FROM " 
			+ ShopContract.TABLE_NAME + " S" 
			+ " INNER JOIN " 
			+ ShopItemContract.TABLE_NAME + " SI"
			+ " INNER JOIN "
			+ ItemContract.TABLE_NAME + " I"
			+ " INNER JOIN "
			+ ItemCategoryContract.TABLE_NAME + " IC";
		
	
	
	
	
	
	/*
			+ " ON " 
			+ "S." + ShopContract.SHOP_ID + "=" + "SI." + ShopItemContract.SHOP_ID
			+ " ON "
			+ "SI." + ShopItemContract.ITEM_ID + "=" + "I." + ItemContract.ITEM_ID
			+ " ON "
			+ "I." + ItemContract.ITEM_CATEGORY_ID + "=" + "IC." + ItemCategoryContract.ITEM_CATEGORY_ID;
	
	*/
	
	
	
	String query = "SELECT DISTINCT " 
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.ITEM_ID + ","
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.SHOP_ID + ","
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.ITEM_PRICE + ","
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.QUANTITY_MULTIPLE + ","
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.QUANTITY_UNIT + ","
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.AVAILABLE_ITEM_QUANTITY + ""
			+ " FROM " 
			+ ShopContract.TABLE_NAME  + "," + ShopItemContract.TABLE_NAME + "," 
			+ ItemContract.TABLE_NAME + "," + ItemCategoryContract.TABLE_NAME
			+ " WHERE " 
			+ ShopContract.TABLE_NAME + "." + ShopContract.SHOP_ID 
			+ "="
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.SHOP_ID
			+ " AND "
			+ ShopItemContract.TABLE_NAME + "." + ShopItemContract.ITEM_ID
			+ "="
			+ ItemContract.TABLE_NAME + "." + ItemContract.ITEM_ID
			+ " AND "
			+ ItemContract.TABLE_NAME + "." + ItemContract.ITEM_CATEGORY_ID
			+ "="
			+ ItemCategoryContract.TABLE_NAME + "." + ItemCategoryContract.ITEM_CATEGORY_ID;
	
	

	if(shopID > 0)
	{
			query = query + " AND "
					+ ShopItemContract.TABLE_NAME 
					+ "."
					+ ShopItemContract.SHOP_ID + " = " + shopID; 	
		
	}
	
	
	if(itemID > 0)
	{	
	
		query = query + " AND "
					+ ShopItemContract.TABLE_NAME
					+ "."
					+ ShopItemContract.ITEM_ID + " = " + itemID;
		
	}
	
	
	
	if(itemCategoryID > 0)
	{

			query = query + " AND "
					+ ItemCategoryContract.TABLE_NAME 
					+ "."
					+ ItemCategoryContract.ITEM_CATEGORY_ID + " = " + itemCategoryID;
			
	}
		
	
	
	/*
		
		if(shopID > 0)
		{
			if(isFirst == true)
			{
			query = query + " WHERE " 
					+ "SI." + ShopItemContract.SHOP_ID + " = " + shopID;
			
			isFirst = false;
			
			} else 
				
			{
				query = query + " AND "
						+ ShopItemContract.SHOP_ID + " = " + shopID; 
			}
			
			
		}
		
		
		if(itemID > 0)
		{
			if(isFirst == true)
			{
				query = query + " WHERE " 
		
						+ "SI." + ShopItemContract.ITEM_ID + " = " + itemID;
				
				isFirst = false;
				
			} else 
			{
				query = query + " AND "
						+ "SI." + ShopItemContract.ITEM_ID + " = " + itemID;
				
			}
			
		}
		
		
		
		if(itemCategoryID > 0)
		{
			

			if(isFirst == true)
			{
				query = query + " WHERE " 
						+ "IC." + ItemCategoryContract.ITEM_CATEGORY_ID + " = " + itemCategoryID;
				
				isFirst = false;
				
			} else 
			{
				query = query + " AND "
						+ "IC." + ItemCategoryContract.ITEM_CATEGORY_ID + " = " + itemCategoryID;
				
			}
		
			
		}
		
		*/
		
		
	System.out.println("query: " + query);
		
		
		
		ArrayList<ShopItem> shopItemList = new ArrayList<ShopItem>();
		
		
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		try {
			
			conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);
			
			stmt = conn.createStatement();
			
			rs = stmt.executeQuery(query);
			
			while(rs.next())
			{
				
				ShopItem shopItem = new ShopItem();
				shopItem.setShopID(rs.getInt(ShopItemContract.SHOP_ID));
				shopItem.setItemID(rs.getInt(ShopItemContract.ITEM_ID));
				shopItem.setAvailableItemQuantity(rs.getInt(ShopItemContract.AVAILABLE_ITEM_QUANTITY));
				shopItem.setItemPrice(rs.getDouble(ShopItemContract.ITEM_PRICE));
				shopItem.setQuantityUnit(rs.getString(ShopItemContract.QUANTITY_UNIT));
				shopItem.setQuantityMultiple(rs.getInt(ShopItemContract.QUANTITY_MULTIPLE));
				
				shopItemList.add(shopItem);
				
			}
			
			System.out.println("Total ShopItems queried = " + shopItemList.size());	
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		

		finally
		
		{
			
			try {
					if(rs!=null)
					{rs.close();}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
			try {
			
				if(stmt!=null)
				{stmt.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			try {
				
				if(conn!=null)
				{conn.close();}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
								
		return shopItemList;

	}
	
}
