package org.nearbyshops.BackupsDAO;

import com.zaxxer.hikari.HikariDataSource;
import org.nearbyshops.Globals.Globals;
import org.nearbyshops.JDBCContract;
import org.nearbyshops.Model.Order;
import org.nearbyshops.ModelEndPoints.OrderEndPoint;

import java.sql.*;
import java.util.ArrayList;

/**
 * Created by sumeet on 7/6/16.
 */
public class OrderService {


    private HikariDataSource dataSource = Globals.getDataSource();

//    private ShopDAO shopDAO = Globals.shopDAO;
//    private ShopItemDAO shopItemDAO = Globals.shopItemDAO;

    public Order placeOrder(Order order, int cartID)
    {

        /*

        1. Copy cart to order
        2. Copy cart_item to order_item
        3. update available_item_quantity from order to shop_item
        4. delete cart_item
        5. delete cart
         */


        int orderID = -1;
        int rowCount = -1;
        int rowCountAvailableItemQuantity= -1;
        int status = 0;

        orderID = copyCartToOrder(cartID);

        if(orderID > 0)
        {
            status = 1;
            rowCount = copyCartItemToOrderItem(orderID,cartID);

        }

        if(rowCount > 0)
        {
            status = 2;
            rowCountAvailableItemQuantity = Globals.shopItemDAO.updateAvailableItemQuantity(orderID);

            // delete cart_item here
            Globals.cartItemService.deleteCartItem(0,cartID);

            // delete cart here
            Globals.cartService.deleteCart(cartID);

        }

        if(orderID>0 && rowCount>0)
        {
            Order tempOrder = readOrder(orderID);

            order.setOrderID(orderID);
            order.setEndUserID(tempOrder.getEndUserID());
            order.setShopID(tempOrder.getShopID());

            if(order.getPickFromShop())
            {
               order.setDeliveryCharges(0);
                order.setStatusPickFromShop(1);

            }else
            {
                order.setDeliveryCharges((int)Globals.shopDAO.getShop(tempOrder.getShopID(),null,null).getDeliveryCharges());
                order.setStatusHomeDelivery(1);
            }

            order.setPaymentReceived(false);
            order.setDeliveryReceived(false);


            updateOrder(order);

            return readOrder(orderID);

        }

        return null;
    }



    public int copyCartToOrder(int cartID)
    {

        String copyCartToOrder = "insert into customer_order " +
                "(end_user_id,shop_id) " +
                "select end_user_id , shop_id from cart where cart_id = " +
                cartID;


        Connection conn = null;
        Statement stmt = null;
        int rowIdOfInsertedRow = -1;



        try {

            conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
                    JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);

            stmt = conn.createStatement();

            rowIdOfInsertedRow = stmt.executeUpdate(copyCartToOrder,Statement.RETURN_GENERATED_KEYS);

            ResultSet rs = stmt.getGeneratedKeys();

            if(rs.next())
            {
                rowIdOfInsertedRow = rs.getInt(1);
            }



            System.out.println("Key autogenerated OrderPFS: " + rowIdOfInsertedRow);


        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        finally
        {

            try {

                if(stmt!=null)
                {stmt.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(conn!=null)
                {conn.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }


        return rowIdOfInsertedRow;
    }


    public int copyCartItemToOrderItem(int orderID, int cartID)
    {



        String copyCartItemToOrderItem =

                "insert into order_item (order_id,item_id, item_price_at_order,item_quantity) " +
                " select " +
                orderID +
                ", shop_item.item_id,item_price, cart_item.item_quantity from cart_item, cart,shop_item " +
                " where " +
                " cart.cart_id = cart_item.cart_id " +
                " and " +
                "shop_item.shop_id = cart.shop_id" +
                " and " +
                " shop_item.item_id = cart_item.item_id " +
                " and " +
                " cart.cart_id = " + cartID;


        Connection conn = null;
        Statement stmt = null;
        int rowCount = -1;



        try {

            conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
                    JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);

            stmt = conn.createStatement();

            rowCount = stmt.executeUpdate(copyCartItemToOrderItem,Statement.RETURN_GENERATED_KEYS);

            //ResultSet rs = stmt.getGeneratedKeys();

            //if(rs.next())
            //{
            //    rowIdOfInsertedRow = rs.getInt(1);
            //}



            System.out.println("Rows updated : copy cart item to order item : " + rowCount);


        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        finally
        {

            try {

                if(stmt!=null)
                {stmt.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(conn!=null)
                {conn.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }


        return rowCount;
    }




    public Order readOrder(int orderID)
    {

        String query = "SELECT * FROM " + Order.TABLE_NAME
                + " WHERE " + Order.ORDER_ID + " = " + orderID;

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        Order order = null;

        try {

            conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
                    JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);

            stmt = conn.createStatement();

            rs = stmt.executeQuery(query);

            while(rs.next())
            {
                order = new Order();
                order.setShopID(rs.getInt(Order.SHOP_ID));
                order.setDeliveryCharges(rs.getInt(Order.DELIVERY_CHARGES));
                order.setDeliveryAddressID(rs.getInt(Order.DELIVERY_ADDRESS_ID));
                order.setEndUserID(rs.getInt(Order.END_USER_ID));
                order.setOrderID(rs.getInt(Order.ORDER_ID));
                order.setPickFromShop(rs.getBoolean(Order.PICK_FROM_SHOP));
                order.setDateTimePlaced(rs.getTimestamp(Order.DATE_TIME_PLACED));
                order.setDeliveryGuySelfID(rs.getInt(Order.DELIVERY_GUY_SELF_ID));

                order.setStatusHomeDelivery(rs.getInt(Order.STATUS_HOME_DELIVERY));
                order.setStatusPickFromShop(rs.getInt(Order.STATUS_PICK_FROM_SHOP));
                order.setDeliveryReceived(rs.getBoolean(Order.DELIVERY_RECEIVED));
                order.setPaymentReceived(rs.getBoolean(Order.PAYMENT_RECEIVED));
            }


            //System.out.println("Total itemCategories queried " + itemCategoryList.size());



        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } finally

        {

            try {
                if(rs!=null)
                {rs.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(stmt!=null)
                {stmt.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(conn!=null)
                {conn.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }

        return order;
    }






    public ArrayList<Order> readOrders(Integer endUserID, Integer shopID,
                                       Boolean pickFromShop,
                                       Integer homeDeliveryStatus,Integer pickFromShopStatus,
                                       Integer deliveryGuyID,
                                       Boolean paymentsReceived,
                                       Boolean deliveryReceived,
                                       String sortBy,
                                       Integer limit, Integer offset)
    {


        String query = "SELECT * FROM " + Order.TABLE_NAME;

        boolean isFirst = true;

        if(endUserID !=null)
        {
            query = query + " WHERE " + Order.END_USER_ID + " = " + endUserID;

            isFirst = false;
        }

        if(shopID != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.SHOP_ID + " = " + shopID;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.SHOP_ID + " = " + shopID;

            }

        }



        if(homeDeliveryStatus != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.STATUS_HOME_DELIVERY + " = " + homeDeliveryStatus;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.STATUS_HOME_DELIVERY + " = " + homeDeliveryStatus;

            }

        }


        if(pickFromShopStatus != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.STATUS_PICK_FROM_SHOP + " = " + pickFromShopStatus;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.STATUS_PICK_FROM_SHOP + " = " + pickFromShopStatus;
            }
        }



        if(pickFromShop != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.PICK_FROM_SHOP + " = " + pickFromShop;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.PICK_FROM_SHOP + " = " + pickFromShop;
            }

        }



        if(deliveryGuyID != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.DELIVERY_GUY_SELF_ID + " = " + deliveryGuyID;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.DELIVERY_GUY_SELF_ID + " = " + deliveryGuyID;
            }

        }



        if(paymentsReceived!=null)
        {

            if(isFirst)
            {
                query = query + " WHERE " + Order.PAYMENT_RECEIVED + " = " + paymentsReceived;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.PAYMENT_RECEIVED + " = " + paymentsReceived;
            }

        }



        if(deliveryReceived!=null)
        {

            if(isFirst)
            {
                query = query + " WHERE " + Order.DELIVERY_RECEIVED + " = " + deliveryReceived;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.DELIVERY_RECEIVED + " = " + deliveryReceived;
            }

        }





        if(sortBy!=null)
        {
            if(!sortBy.equals(""))
            {
                String queryPartSortBy = " ORDER BY " + sortBy;

                query = query + queryPartSortBy;
            }
        }



        if(limit != null)
        {

            String queryPartLimitOffset = "";

            if(offset>0)
            {
                queryPartLimitOffset = " LIMIT " + limit + " " + " OFFSET " + offset;

            }else
            {
                queryPartLimitOffset = " LIMIT " + limit + " " + " OFFSET " + 0;
            }

            query = query + queryPartLimitOffset;
        }




        ArrayList<Order> ordersList = new ArrayList<Order>();

        Connection connection = null;
        Statement statement = null;
        ResultSet rs = null;

        try {

            connection = dataSource.getConnection();
            statement = connection.createStatement();


            rs = statement.executeQuery(query);

            while(rs.next())
            {

                Order order = new Order();
                order.setShopID(rs.getInt(Order.SHOP_ID));
                order.setDeliveryCharges(rs.getInt(Order.DELIVERY_CHARGES));
                order.setDeliveryAddressID(rs.getInt(Order.DELIVERY_ADDRESS_ID));
                order.setEndUserID(rs.getInt(Order.END_USER_ID));
                order.setOrderID(rs.getInt(Order.ORDER_ID));
                order.setPickFromShop(rs.getBoolean(Order.PICK_FROM_SHOP));
                order.setDateTimePlaced(rs.getTimestamp(Order.DATE_TIME_PLACED));
                order.setDeliveryGuySelfID(rs.getInt(Order.DELIVERY_GUY_SELF_ID));


                order.setStatusHomeDelivery(rs.getInt(Order.STATUS_HOME_DELIVERY));
                order.setStatusPickFromShop(rs.getInt(Order.STATUS_PICK_FROM_SHOP));
                order.setDeliveryReceived(rs.getBoolean(Order.DELIVERY_RECEIVED));
                order.setPaymentReceived(rs.getBoolean(Order.PAYMENT_RECEIVED));

                ordersList.add(order);

            }



        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


        finally

        {

            try {
                if(rs!=null)
                {rs.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(statement!=null)
                {statement.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(connection!=null)
                {connection.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }


        return ordersList;
    }




    public OrderEndPoint endPointMetaDataOrders(Integer endUserID, Integer shopID,
                                       Boolean pickFromShop,
                                       Integer homeDeliveryStatus,Integer pickFromShopStatus,
                                       Integer deliveryGuyID,
                                       Boolean paymentsReceived,
                                       Boolean deliveryReceived,
                                       String sortBy,
                                       Integer limit, Integer offset)
    {

        String query = "SELECT " +
                        "count( DISTINCT " + Order.ORDER_ID + ") as item_count" +
                        " FROM " + Order.TABLE_NAME;


        boolean isFirst = true;

        if(endUserID !=null)
        {
            query = query + " WHERE " + Order.END_USER_ID + " = " + endUserID;

            isFirst = false;
        }

        if(shopID != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.SHOP_ID + " = " + shopID;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.SHOP_ID + " = " + shopID;

            }

        }



        if(homeDeliveryStatus != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.STATUS_HOME_DELIVERY + " = " + homeDeliveryStatus;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.STATUS_HOME_DELIVERY + " = " + homeDeliveryStatus;

            }

        }


        if(pickFromShopStatus != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.STATUS_PICK_FROM_SHOP + " = " + pickFromShopStatus;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.STATUS_PICK_FROM_SHOP + " = " + pickFromShopStatus;
            }
        }



        if(pickFromShop != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.PICK_FROM_SHOP + " = " + pickFromShop;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.PICK_FROM_SHOP + " = " + pickFromShop;
            }

        }



        if(deliveryGuyID != null)
        {
            if(isFirst)
            {
                query = query + " WHERE " + Order.DELIVERY_GUY_SELF_ID + " = " + deliveryGuyID;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.DELIVERY_GUY_SELF_ID + " = " + deliveryGuyID;
            }

        }



        if(paymentsReceived!=null)
        {

            if(isFirst)
            {
                query = query + " WHERE " + Order.PAYMENT_RECEIVED + " = " + paymentsReceived;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.PAYMENT_RECEIVED + " = " + paymentsReceived;
            }

        }



        if(deliveryReceived!=null)
        {

            if(isFirst)
            {
                query = query + " WHERE " + Order.DELIVERY_RECEIVED + " = " + deliveryReceived;

                isFirst = false;

            }else
            {
                query = query + " AND " + Order.DELIVERY_RECEIVED + " = " + deliveryReceived;
            }

        }





        if(sortBy!=null)
        {
            if(!sortBy.equals(""))
            {
                String queryPartSortBy = " ORDER BY " + sortBy;

                query = query + queryPartSortBy;
            }
        }



        if(limit != null)
        {

            String queryPartLimitOffset = "";

            if(offset>0)
            {
                queryPartLimitOffset = " LIMIT " + limit + " " + " OFFSET " + offset;

            }else
            {
                queryPartLimitOffset = " LIMIT " + limit + " " + " OFFSET " + 0;
            }

            query = query + queryPartLimitOffset;
        }



        OrderEndPoint endPoint = new OrderEndPoint();

        Connection connection = null;
        Statement statement = null;
        ResultSet rs = null;

        try {

            connection = dataSource.getConnection();
            statement = connection.createStatement();
            rs = statement.executeQuery(query);


            while(rs.next())
            {
                endPoint.setItemCount(rs.getInt("item_count"));
            }

            System.out.println("Item Count : " + endPoint.getItemCount());



        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


        finally

        {

            try {
                if(rs!=null)
                {rs.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(statement!=null)
                {statement.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(connection!=null)
                {connection.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }


        return endPoint;
    }






    public int updateOrder(Order order)
    {
        String updateStatementPart = "UPDATE " + Order.TABLE_NAME

                + " SET "
                + Order.END_USER_ID + " = " + " " + order.getEndUserID() + " " + ","
                + " " + Order.SHOP_ID + " = " + " " + order.getShopID() + " " + ","
                + " " + Order.STATUS_HOME_DELIVERY + " = " + " " + order.getStatusHomeDelivery() + " " + ","
                + " " + Order.STATUS_PICK_FROM_SHOP + " = " + " " + order.getStatusPickFromShop() + " " + ","
                + " " + Order.PAYMENT_RECEIVED + " = " + " " + order.getPaymentReceived() + " " + ","
                + " " + Order.DELIVERY_RECEIVED + " = " + " " + order.getDeliveryReceived() + " " + ","
                + " " + Order.DELIVERY_CHARGES + " = " + " " + order.getDeliveryCharges() + " " + ","
                + " " + Order.DELIVERY_ADDRESS_ID + " = " + " " + order.getDeliveryAddressID() + " " + ",";


        String deliveryAddressPart = "";



        String deliveryVehiclePart = "";

        if(order.getDeliveryGuySelfID() == 0)
        {
            //deliveryVehiclePart = " " + OrderPFS.DELIVERY_GUY_SELF_ID + " = " + " " +   + " " + ",";
            //deliveryVehiclePart = " " + OrderPFS.DELIVERY_GUY_SELF_ID + " = " + " " + " " + ",";

        }else
        {
            deliveryVehiclePart = " " + Order.DELIVERY_GUY_SELF_ID + " = " + " " + order.getDeliveryGuySelfID() + " " + ",";
        }


        String updatePartLast = " " + Order.PICK_FROM_SHOP + " = " + " " + order.getPickFromShop() + " " + ""
                + " WHERE " + Order.ORDER_ID + " = "
                + order.getOrderID();


        String updateStatement = updateStatementPart + deliveryVehiclePart + updatePartLast;



        Connection conn = null;
        Statement stmt = null;
        int updatedRows = -1;

        try {

            conn = DriverManager.getConnection(JDBCContract.CURRENT_CONNECTION_URL,
                    JDBCContract.CURRENT_USERNAME,JDBCContract.CURRENT_PASSWORD);

            stmt = conn.createStatement();

            updatedRows = stmt.executeUpdate(updateStatement);


            System.out.println("Total rows updated: " + updatedRows);

            //conn.close();

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        finally

        {

            try {

                if(stmt!=null)
                {stmt.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {

                if(conn!=null)
                {conn.close();}
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }

        return updatedRows;
    }

}
